config/routes.rb
RulesMachine::Application.routes.draw do
  resources :rules

  root(:to => 'rules#index')

end

app/models/rule.rb
class Rule < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/.#rules_controller.rb
timothyclayton@Mach19-MacBook-Pro-1.local.12244

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    respond_to(:html, :json, :js)
end

app/controllers/rules_controller.rb
require "base64"
require 'api_calls.rb'
class RulesController < ApplicationController
  include ApiCalls

  def index
    @rules = get_rules

    respond_to do |format|
      format.html
      format.json { render json: @rules }
    end
  end

  def show
    @rule = get_rule(params[:id])
  end

  def new
    #call GET/device_instance endpoint
    @device_instances = get_device_instances
    device_ids = []
    @device_device_instances = {}

    @device_instances.each do |di|
      device_ids << di[:device_id]
      if @device_device_instances[di[:device_id]]
        @device_device_instances[di[:device_id]]
        @device_device_instances[di[:device_id]] << di[:_id]
      else
        @device_device_instances[di[:device_id]] = [di[:_id]]
      end
    end
    device_ids = device_ids.uniq if device_ids.length > 0
    @device_device_instances = @device_device_instances.to_json

    #call GET/device endpoint
    @devices = []
    device_ids.each do |id|
      @devices << get_device(id)
    end

    #get all device payloads
    @device_properties = {}
    @devices.each do |device|
      device[:payloads] = [] if !device[:payloads]
      device_props = []
      device[:payloads].each do |payload|
        device_props << payload[:key_name]
      end if @device_properties[device[:_id]] = device_props
      @device_properties[device[:id]] = device_props
    end
    @device_properties = @device_properties.to_json

    # Call endpoint to retrieve all possible rule conditions
    @join_rule_conditions = get_join_rule_conditions.to_json
    @comparison_rule_conditions = get_comparison_rule_conditions.to_json

    respond_to do |format|
      format.html
      format.json { render json: @rule }
    end
  end

  def create
    rule = create_rule(params[:rule_json])
    if rule
      redirect_to rules_path
    else
      render action: 'new'
    end
  end

  def destroy
    @rule = delete_rule(params[:id])
    redirect_to rules_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RulesMachine</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <header>
        <nav>
          <div id='publogo'>
            <a href="/" class="logo_link"><img alt="Logo" class="logo_size" id="publogoimg" src="/assets/logo.png" /></a>
          </div>
          <div class='welcome'>Welcome!</div>
        </nav>
        <div class="drop-shadow lifted">
          <div class="red-stripe"></div>
          <div class="black-stripe"></div>
          <p id="wizard-description">
            This application allows you to step through creating a rule for a device type or device instance on the machineshop platform and see the JSON that's created through this process.
          </p>
        </div>
      </header>
      <%= yield %>
    </div>
  </body>
</html>

app/views/rules/_form.html.haml
.profile_container

  = form_tag(rules_path, :method => 'post') do

    %div#rule_basics
      / Description, device/device_instances, condition_type
      %div
        = hidden_field_tag :device_properties, @device_properties # json used for populating dropdowns
        = hidden_field_tag :device_device_instances, @device_device_instances
        = hidden_field_tag :join_rule_conditions, @join_rule_conditions
        = hidden_field_tag :comparison_rule_conditions, @comparison_rule_conditions
        = hidden_field_tag :rule_json

      %div
        .form_label
          = label_tag :description
        .form_field
          = text_field_tag 'description', nil, required: true

      %div#device_selection

        = radio_button_tag('device_selection', 'rule_devices', true)
        Create for all devices of a type.
        %br
        = radio_button_tag('device_selection', 'rule_device_instances', false)
        Create for a specific device instance.
      %div#rule_devices
        .form_label
          = label_tag :device_type
        .form_field
          %select#device_ids
            - @devices.each do |d|
              %option{:value => d[:_id]}
                = d[:name]
      %div#rule_device_instances
        .form_label
          = label_tag :device_instance_name
        .form_field
          %select#device_instance_ids
            - @device_instances.each do |di|
              %option{:value => di[:_id]}
                = di[:name]
      %div
        .form_label
          = label_tag "What type of condition should this rule have?"
        %div#rule_condition_selector.form_field
          = select(:rule_condition, :_type, [['A few conditions that must all be true.', 'and_rule_condition'],['A few conditions where only one must be true.', 'or_rule_condition'], ['A condition that should not be true.', 'not_rule_condition'], ['A value should be equal to a threshold.', 'equal_rule_condition'], ['A value should be greater than a threshold.', 'greater_than_rule_condition'], ['A value should be greater than or equal to a threshold.', 'greater_than_equal_rule_condition'], ['A value should be less than a threshold.', 'less_than_rule_condition'], ['A value should be less than or equal to a threshold.', 'less_than_equal_rule_condition'], ['Device location relative to a fixed point.','near_rule_condition']])
        %br

    %div#condition_attributes

    %div#sub_conditions
    / Specify sub conditions for joining conditions at the top level.
    %div#then_actions
      / Create all the then_actions for the rule.
      Do this if the rule condition is met:
    %div#else_actions
      / Create all the actions that happen if the condition is not met.
      Do this if the rule condition is not met:
    %div#confirmation
    / Show how the rule would read in plain English (hopefully).
    %br
      / = @rule
    .form-actions
      = link_to '<< Back', 'javascript:void(0)', :onclick => 'RuleWizardBack()', :class => 'btn back-btn'
      = link_to 'Next >>', 'javascript:void(0)', :onclick => 'RuleWizardNext()', :class => 'btn next-btn'

      %button.btn.sbt-btn(type='submit') Submit
      = link_to 'Cancel', rules_path, :class => "btn"

app/views/rules/deactivate.js.haml
$(".btn-group[student_id=<%=j @student.id.to_s %>]").replaceWith("<%=j render :partial => 'sessions/sign_in', :locals => {:session => @session, :student => @student} %>");

app/views/rules/edit.html.haml
.padded-container
  .headline
    %h1 Edit Rule

= render 'form'

app/views/rules/index.html.haml
.padded-container

  %h1.span1 Rule Wizard
  %a.btn-new-rule.span2(href=new_rule_path) + New Rule
  .table_container

    %table.table.table-striped
      %tr
        %td
          DESCRIPTION
        %td
          DATE CREATED
        %td.delete-hdr
          DELETE
      - @rules.each do |rule|
        %tr
          %td.rules-list
            = rule[:description]
            %p.notice
              = rule[:plain_english]
          %td
            = rule[:created_at].to_time.strftime("%m/%d/%Y")
          %td.delete
            = link_to image_tag('remove-icon.png', :alt => 'Delete', :title => 'Delete'), rule_path(rule[:_id]), :method => :delete, :data => {:confirm => 'Are you sure?'}
            / = will_paginate @rules

app/views/rules/new.html.haml
%h1 New Rule

= render 'form'

/ = link_to 'Back', rules_path

app/views/rules/rule_basics.haml
This is where you start!

app/views/rules/show.html.haml
%p#notice= notice

=@rule[:plain_english]
/ = @rule.plain_english

/ = link_to 'Edit', edit_rule_path(@rule)

= link_to 'Back', rules_path

app/views/shared/_form_errors.html.haml
- if obj.errors.any?
  .alert.alert-error
    %h4= t('views.errors.fix')
    %ul.unstyled
      - obj.errors.full_messages.each do |msg|
        %li= msg